fix: using new hypershift dump guest cluster policies to dump guest cluster content
The hypershift CLI now exits on error if fail-on-error policy is set; this allows a proper
fallback to dump the guest cluster content by directly targeting the kube-apiserver service
(direct-kube-api-service-access policy) on MC clusters used by ROSA HCP.

ref: https://redhat.atlassian.net/browse/ROSAENG-14082

Signed-off-by: Nicolas Grauss <ngrauss@redhat.com>

diff --git a/collection-scripts/gather_utils b/collection-scripts/gather_utils
--- a/collection-scripts/gather_utils
+++ b/collection-scripts/gather_utils
@@ -240,10 +240,10 @@ dump_hostedcluster() {
 
   log "Collecting must-gather for hosted cluster '${HC_NAME}' in namespace '${HC_NAMESPACE}'"
   hypershift_cmd=("${HYPERSHIFT}" dump cluster --artifact-dir "${BASE_COLLECTION_PATH}" --name "${HC_NAME}" --namespace "${HC_NAMESPACE}")
-  if ! "${hypershift_cmd[@]}" --dump-guest-cluster; then
-    log "WARN" "Failed to collect must-gather for hosted cluster '${HC_NAME}' in namespace '${HC_NAMESPACE}' using --dump-guest-cluster. Trying --dump-guest-cluster-through-kube-service."
-    if ! "${hypershift_cmd[@]}" --dump-guest-cluster-through-kube-service; then
-      log "ERROR" "Failed to collect must-gather for hosted cluster '${HC_NAME}' in namespace '${HC_NAMESPACE}' using --dump-guest-cluster-through-kube-service."
+  if ! "${hypershift_cmd[@]}" --dump-guest-cluster=fail-on-error; then
+    log "WARN" "Failed to collect must-gather for hosted cluster '${HC_NAME}' in namespace '${HC_NAMESPACE}' using --dump-guest-cluster. Trying --dump-guest-cluster=fail-on-error,direct-kube-api-service-access."
+    if ! "${hypershift_cmd[@]}" --dump-guest-cluster=fail-on-error,direct-kube-api-service-access; then
+      log "ERROR" "Failed to collect must-gather for hosted cluster '${HC_NAME}' in namespace '${HC_NAMESPACE}' using --dump-guest-cluster=fail-on-error,direct-kube-api-service-access."
       return 1
     fi
   fi
